dependencies:
  - python=3.6.2
  - scikit-learn
  - numpy
  - pandas
  - pip:
    - azureml-defaults
    - azureml-train-automl
    - azureml-pipeline
    - azureml-pipeline-steps
    - kaggle
    - cryptography==38.0.1
    - dataclasses==0.6
    - flatbuffers==22.9.24
    - knack==0.10.0
    - paramiko==2.11.0
    - pkginfo==1.8.3
    - psutil==5.9.3
    - urllib3==1.26.12